
name: Deploy React App to AWS S3

on:
  push:
    branches:
      - main

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3


      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' 

      - name: Dependencias
        run: npm install

      - name: Build React app
        run: npm run build
        env:
          CI: false

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }} # 'us-east-1'

      - name: Deploy to S3 #Remember to change this with the one provided at the end of the infrastructure deploy
        run: |
          aws s3 sync ./build s3://bucket-prueba-despliegue-website-terraform-githubactionsv2 --delete 
